name: Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Change this to your Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build and publish blog
        run: |
          bundle exec rake build
          bundle exec rake publish
